# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Timeout for commands executed by starship (in milliseconds).
command_timeout = 1000

format = """
$time\
$env_var\
$username\
$hostname\
$shlvl\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$python\
$kubernetes\
$memory_usage\
$cmd_duration\
$line_break\
$jobs\
$battery\
$status\
$character"""

[status]
disabled = false
symbol = 'x'

[time]
format = '[$time]($style) '
disabled = false

[directory]
truncation_length = 256
truncate_to_repo = false
read_only = " 󰌾"

[env_var]
format = '[$env_value]($style) '
variable = 'DEVENV_PROMPT'
style = ''

[env_var.GOPATH]
format = '[]($style) '
style = ''

[memory_usage]
disabled = false
symbol = "󰍛 "

[git_status]
ignore_submodules = true

[python]
# Don't trigger for files with the py extension
detect_extensions = []
symbol = " "

[kubernetes]
format = '[$symbol$context( \($namespace\))]($style) '
disabled = false

[git_branch]
symbol = " "

[git_commit]
tag_symbol = '  '

