# Timeout for commands executed by starship (in milliseconds).
command_timeout = 1000

format = """
$time\
$env_var\
$username\
$hostname\
$shlvl\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$python\
$memory_usage\
$cmd_duration\
$kubernetes\
$line_break\
$jobs\
$battery\
$status\
$character"""

[status]
disabled = false
symbol = 'x'

[time]
format = '[$time]($style) '
disabled = false

[directory]
truncation_length = 256
truncate_to_repo = false

[env_var]
format = '[$env_value]($style) '
variable = 'DEVENV_PROMPT'
style = ''

[memory_usage]
disabled = false

[git_status]
ignore_submodules = true

[python]
# Don't trigger for files with the py extension
detect_extensions = []

# ~/.config/starship.toml

[kubernetes]
disabled = false
