[general]
import = [ "~/.local/share/nvim/plugged/tokyonight.nvim/extras/alacritty/tokyonight_moon.toml" ]

[colors]
# transparent_background_colors = true
transparent_background_colors = false

[font]
size = 12.0

[font.bold]
family = "FiraCode Nerd Font"

[font.bold_italic]
family = "FiraCode Nerd Font"

[font.italic]
family = "FiraCode Nerd Font"

[font.normal]
family = "FiraCode Nerd Font"

[font.offset]
y = 1

[window]
opacity = 0.95

[scrolling]
history = 100000

[terminal]
osc52 = "CopyPaste"

[keyboard]
bindings = [
{ key = "ArrowUp",   mods = "Command",      mode = "~Vi|~Search", action = "ToggleViMode" },
{ key = "ArrowUp",   mods = "Command",      mode = "~Vi|~Search", action = "SearchBackward" },
{ key = "ArrowUp",   mods = "Command",      mode = "~Vi|~Search", chars = "❯" },
{ key = "ArrowUp",   mods = "Command",      mode = "~Vi|~Search", action = "SearchConfirm" },
{ key = "ArrowUp",   mods = "Command",      mode = "Vi",          action = "SearchBackward" },
{ key = "ArrowUp",   mods = "Command",      mode = "Vi",          chars = "❯" },
{ key = "ArrowUp",   mods = "Command",      mode = "Vi",          action = "SearchConfirm" },
{ key = "ArrowDown", mods = "Command",      mode = "~Vi|~Search", action = "ToggleViMode" },
{ key = "ArrowDown", mods = "Command",      mode = "~Vi|~Search", action = "SearchForward" },
{ key = "ArrowDown", mods = "Command",      mode = "~Vi|~Search", chars = "❯" },
{ key = "ArrowDown", mods = "Command",      mode = "~Vi|~Search", action = "SearchConfirm" },
{ key = "ArrowDown", mods = "Command",      mode = "Vi",          action = "SearchForward" },
{ key = "ArrowDown", mods = "Command",      mode = "Vi",          chars = "❯" },
{ key = "ArrowDown", mods = "Command",      mode = "Vi",          action = "SearchConfirm" },
]

# [debug]
# log_level = "Trace"
# persistent_logging = true
# print_events = false
